-- 사용자 테이블
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID VARCHAR(50) PRIMARY KEY COMMENT '아이디',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '비밀번호',
    USER_NAME VARCHAR(100) NOT NULL COMMENT '이름',
    USER_EMAIL VARCHAR(100) COMMENT '이메일',
    USER_PHONE VARCHAR(20) NOT NULL COMMENT '전화번호',
    PROFILE_IMAGE VARCHAR(255) COMMENT '프로필 이미지',
    ROLE VARCHAR(20) NOT NULL DEFAULT 'NORMAL_USER' COMMENT '역할',
    STATUS CHAR(1) DEFAULT 'Y' COMMENT '상태',
    DELETE_REQUEST CHAR(1) DEFAULT 'N' COMMENT '삭제 요청',
    DELETE_REQUESTED_AT DATETIME COMMENT '삭제 요청일시',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 지점 테이블
CREATE TABLE IF NOT EXISTS BRANCHES (
    BRANCH_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '지점 아이디',
    BRANCH_NAME VARCHAR(50) NOT NULL COMMENT '지점 이름',
    BRANCH_ADDRESS VARCHAR(255) NOT NULL COMMENT '지점 주소',
    BRANCH_PHONE VARCHAR(20) NOT NULL COMMENT '지점 전화번호',
    BRANCH_MEMO TEXT COMMENT '지점 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 지점 관리자 테이블
CREATE TABLE IF NOT EXISTS BRANCH_MANAGERS (
    BRANCH_MANAGER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '지점 관리자 아이디',
    BRANCH_ID INT NOT NULL COMMENT '지점 아이디',
    USER_ID VARCHAR(50) NOT NULL COMMENT '아이디',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 대학교 테이블
CREATE TABLE IF NOT EXISTS SCHOOLS (
    SCHOOL_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '대학교 아이디',
    SCHOOL_NAME VARCHAR(50) COMMENT '대학교 이름',
    SCHOOL_ADDRESS VARCHAR(255) COMMENT '대학교 주소',
    SCHOOL_PHONE VARCHAR(20) COMMENT '대학교 전화번호',
    SCHOOL_URL VARCHAR(255) COMMENT '대학교 웹사이트',
    ADMISSION_INFO_URL VARCHAR(255) COMMENT '대학교 입학안내',
    SCHOOL_LOGO_URL VARCHAR(255) COMMENT '대학교 로고 이미지 경로',
    SCHOOL_LOGO_FILENAME VARCHAR(255) COMMENT '대학교 로고 이미지 파일명',
    SCHOOL_LOGO_ORIGINAL_FILENAME VARCHAR(255) COMMENT '대학교 로고 이미지 원본 파일명',
    SCHOOL_LOGO VARCHAR(255) NOT NULL DEFAULT 'none' COMMENT '대학교 로고 선택',
    SCHOOL_MEMO TEXT COMMENT '대학교 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 학과 테이블
CREATE TABLE IF NOT EXISTS DEPARTMENTS (
    DEPARTMENT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '학과 아이디',
    DEPARTMENT_NAME VARCHAR(50) NOT NULL COMMENT '학과 이름',
    DEPARTMENT_ADDRESS VARCHAR(255) COMMENT '학과 주소',
    DEPARTMENT_PHONE VARCHAR(20) COMMENT '학과 전화번호',
    DEPARTMENT_URL VARCHAR(255) COMMENT '학과 웹사이트',
    DEPARTMENT_MEMO TEXT COMMENT '학과 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 시/도 테이블
CREATE TABLE IF NOT EXISTS PROVINCES (
    PROVINCE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '시/도 아이디',
    PROVINCE_NAME VARCHAR(50) NOT NULL COMMENT '시/도 이름',
    PROVINCE_MEMO TEXT COMMENT '시/도 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 구/군 테이블
CREATE TABLE IF NOT EXISTS DISTRICTS (
    DISTRICT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '구/군 아이디',
    PROVINCE_ID INT NOT NULL COMMENT '시/도 아이디',
    DISTRICT_NAME VARCHAR(50) NOT NULL COMMENT '구/군 이름',
    DISTRICT_MEMO TEXT COMMENT '구/군 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 고등학교 테이블
CREATE TABLE IF NOT EXISTS HIGH_SCHOOLS (
    HIGH_SCHOOL_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '고등학교 아이디',
    PROVINCE_ID INT NOT NULL COMMENT '시/도 아이디',
    DISTRICT_ID INT NOT NULL COMMENT '구/군 아이디',
    HIGH_SCHOOL_NAME VARCHAR(50) COMMENT '고등학교 이름',
    HIGH_SCHOOL_ADDRESS VARCHAR(255) COMMENT '고등학교 주소',
    HIGH_SCHOOL_PHONE VARCHAR(20) COMMENT '고등학교 전화번호',
    HIGH_SCHOOL_WEBSITE VARCHAR(255) COMMENT '고등학교 웹사이트',
    HIGH_SCHOOL_MEMO TEXT COMMENT '고등학교 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 수능 교과목 테이블
CREATE TABLE IF NOT EXISTS CSAT_SUBJECTS (
    CSAT_SUBJECT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '수능 교과목 아이디',
    CSAT_SUBJECT_NAME VARCHAR(50) NOT NULL COMMENT '수능 교과목 이름',
    CSAT_SUBJECT_TYPE VARCHAR(20) NOT NULL COMMENT '수능 교과목 타입',
    CSAT_SUBJECT_MEMO TEXT COMMENT '수능 교과목 메모',    
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 실기 교과목 테이블
CREATE TABLE IF NOT EXISTS PHYSICAL_SUBJECTS (
    PHYSICAL_SUBJECT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '실기 교과목 아이디',
    PHYSICAL_SUBJECT_NAME VARCHAR(50) NOT NULL COMMENT '실기 교과목 이름',
    PHYSICAL_SUBJECT_MEMO TEXT COMMENT '실기 교과목 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 입시 요강 테이블
CREATE TABLE IF NOT EXISTS ADMISSIONS (
    ADMISSION_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '입시 요강 아이디',
    ADMISSION_YEAR INT NOT NULL COMMENT '입시 요강 연도',
    ADMISSION_TYPE VARCHAR(1) NOT NULL DEFAULT '가' COMMENT '입시 요강 구분',
    SCHOOL_ID INT NOT NULL COMMENT '학교 아이디',
    DEPARTMENT_ID INT NOT NULL COMMENT '학과 아이디',
    EARLY_ADMISSION VARCHAR(20) NOT NULL COMMENT '수시 입시 여부',
    REGULAR_ADMISSION VARCHAR(20) NOT NULL COMMENT '정시 입시 여부',
    ADMISSION_MEMO TEXT COMMENT '입시 요강 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);



