-- 사용자 테이블
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID VARCHAR(50) PRIMARY KEY COMMENT '아이디',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '비밀번호',
    USER_NAME VARCHAR(100) NOT NULL COMMENT '이름',
    USER_EMAIL VARCHAR(100) COMMENT '이메일',
    USER_PHONE VARCHAR(20) NOT NULL COMMENT '전화번호',
    PROFILE_IMAGE VARCHAR(255) COMMENT '프로필 이미지',
    ROLE VARCHAR(20) NOT NULL DEFAULT 'NORMAL_USER' COMMENT '역할',
    STATUS CHAR(1) DEFAULT 'Y' COMMENT '상태',
    DELETE_REQUEST CHAR(1) DEFAULT 'N' COMMENT '삭제 요청',
    DELETE_REQUESTED_AT DATETIME COMMENT '삭제 요청일시',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 관리자 정보
-- INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, USER_EMAIL, USER_PHONE, ROLE, CREATED_BY, UPDATED_BY)
-- SELECT 'sung2ne', '$2a$10$xM/rrCyLBfVzQNqpW3ODvePFPv0H.43/Ezpp17fnistdwIE0Fs8k.', '정필성', 'admin@seoulfitness.kr', '010-1234-5678', '관리자', 'sung2ne', 'sung2ne'
-- WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE ROLE = '관리자');
-- 지점 관리자
INSERT INTO USERS (USER_ID, PASSWORD, USER_NAME, USER_PHONE, ROLE, CREATED_BY, UPDATED_BY)
SELECT 'rpm-sixty1540', '$10$d2IPI.nP9D7Dq.TH6bZWWurHV2HaGOUt.NB7.T1VwGSMIBP.Vob5a', '고웅', '010-8976-1540', '지점 관리자', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE ROLE = '지점 관리자');

-- 지점 테이블
CREATE TABLE IF NOT EXISTS BRANCHES (
    BRANCH_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '지점 아이디',
    BRANCH_NAME VARCHAR(50) NOT NULL COMMENT '지점 이름',
    BRANCH_ADDRESS VARCHAR(255) NOT NULL COMMENT '지점 주소',
    BRANCH_PHONE VARCHAR(20) NOT NULL COMMENT '지점 전화번호',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 1, '김포·검단점', '인천 서구 검단로 842 상가동 302 월드중앙상가 3층', '032-569-0567', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '김포·검단점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 2, '마포점', '서울시 종로구 율곡로 75 계동 현대사옥내 서울휘트니스', '02-711-5333	', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '마포점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 3, '목동점', '서울시 양천구 신원로389 남부빌딩 7층', '02-2648-2577', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '목동점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 4, '보라매점', '서울시 영등포구 신풍로113 시원빌딩 9층', '02-842-2577', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '보라매점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 5, '부천점', '부천시 중동로 71번길 43', '032-661-2114', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '부천점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 6, '수원점', '수원시 대평로 128 파크프라자 1층, 3층, 7층', '031-269-2031', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '수원점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 7, '안산·시흥점', '안산시 단원구 광덕서로82 고잔동 한난법조빌딩 6층', '031-403-2388', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '안산·시흥점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 8, '안양점', '안양시 동안구 호계동 1029-17 보영빌딩 4층, 5층', '031-429-4264', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '안양점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 9, '인천 연수구점', '인천 연수구 새말로 134 세경아파트상가 1층, 2층', '032-815-0073', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '인천 연수구점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 10, '종로·성북점', '서울시 종로구 율곡로 75 현대사옥내 서울휘트니스', '02-395-3478', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '종로·성북점');
INSERT INTO BRANCHES (BRANCH_ID,BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE, CREATED_BY, UPDATED_BY)
SELECT 11, '홍제점', '서울시 종로구 율곡로 75 계동 현대사옥내 서울휘트니스', '02-395-3478', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCHES WHERE BRANCH_NAME = '홍제점');

-- 지점 관리자 테이블
CREATE TABLE IF NOT EXISTS BRANCH_MANAGERS (
    BRANCH_MANAGER_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '지점 관리자 아이디',
    BRANCH_ID INT NOT NULL COMMENT '지점 아이디',
    USER_ID VARCHAR(50) NOT NULL COMMENT '아이디',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);
INSERT INTO BRANCH_MANAGERS (BRANCH_ID, USER_ID, CREATED_BY, UPDATED_BY)
SELECT 11, 'rpm-sixty1540', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCH_MANAGERS WHERE BRANCH_ID = 11 AND USER_ID = 'rpm-sixty1540');
INSERT INTO BRANCH_MANAGERS (BRANCH_ID, USER_ID, CREATED_BY, UPDATED_BY)
SELECT 2, 'rpm-sixty1540', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM BRANCH_MANAGERS WHERE BRANCH_ID = 2 AND USER_ID = 'rpm-sixty1540');

-- 대학교 테이블
CREATE TABLE IF NOT EXISTS SCHOOLS (
    SCHOOL_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '대학교 아이디',
    SCHOOL_NAME VARCHAR(50) COMMENT '대학교 이름',
    SCHOOL_ADDRESS VARCHAR(255) COMMENT '대학교 주소',
    SCHOOL_PHONE VARCHAR(20) COMMENT '대학교 전화번호',
    SCHOOL_URL VARCHAR(255) COMMENT '대학교 웹사이트',
    ADMISSION_INFO_URL VARCHAR(255) COMMENT '대학교 입학안내',
    SCHOOL_LOGO_URL VARCHAR(255) COMMENT '대학교 로고 이미지 경로',
    SCHOOL_LOGO_FILENAME VARCHAR(255) COMMENT '대학교 로고 이미지 파일명',
    SCHOOL_LOGO_ORIGINAL_FILENAME VARCHAR(255) COMMENT '대학교 로고 이미지 원본 파일명',
    SCHOOL_LOGO VARCHAR(255) NOT NULL DEFAULT 'none' COMMENT '대학교 로고 선택',
    SCHOOL_MEMO VARCHAR(255) COMMENT '대학교 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);
INSERT INTO SCHOOLS (SCHOOL_NAME, CREATED_BY, UPDATED_BY)
SELECT '가톨릭관동대학교', 'sung2ne', 'sung2ne'
WHERE NOT EXISTS (SELECT 1 FROM SCHOOLS WHERE SCHOOL_NAME = '가톨릭관동대학교');

-- 시/도 테이블
CREATE TABLE IF NOT EXISTS PROVINCES (
    PROVINCE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '시/도 아이디',
    PROVINCE_NAME VARCHAR(50) NOT NULL COMMENT '시/도 이름',
    PROVINCE_MEMO VARCHAR(255) COMMENT '시/도 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);

-- 구/군 테이블
CREATE TABLE IF NOT EXISTS DISTRICTS (
    DISTRICT_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '구/군 아이디',
    PROVINCE_ID INT NOT NULL COMMENT '시/도 아이디',
    DISTRICT_NAME VARCHAR(50) NOT NULL COMMENT '구/군 이름',
    DISTRICT_MEMO VARCHAR(255) COMMENT '구/군 메모',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    CREATED_BY VARCHAR(50) COMMENT '등록한 사람',
    UPDATED_BY VARCHAR(50) COMMENT '수정한 사람'
);




















